config/routes.rb
HomestuffHAML::Application.routes.draw do


  get "sessions/new", as: :new_session
  post "sessions/create", controller: "sessions", action: "create"
  delete "sessions", controller: "sessions", action: "destroy", as: :delete_session

  get "items/autocomplete_item_name", controller: 'items', action: 'autocomplete_item_name', as: :autocomplete_item_name

  resources :users  
  resources :items
  
  root to: "items#index"  
  
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/condition.rb
class Condition < ActiveRecord::Base
end

app/models/item.rb
class Item < ActiveRecord::Base

  validates_presence_of :name
  
  belongs_to :user
  belongs_to :category
  belongs_to :condition

end

app/models/user.rb
class User < ActiveRecord::Base

  validates_presence_of :first_name, :last_name
  
  has_secure_password

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, :presence => true,
                    :format   => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false }
                    
  has_many :items, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user
  helper_method :logged_in?

  def logged_in?
    if session[:uid].present?
      @user = User.find(session[:uid])
    end
  end
    
  def require_user
    redirect_to new_user_url unless logged_in?
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_filter :require_user
  autocomplete :item, :name, :full => true, :autofocus => true
  
  def index
    # @items = @user.items.scoped
    @items = @user.items

    if params[:field].present?
      search_term = params[:field][:item_name]
      @items = @items.where('name like ?', "%#{search_term}%")
    end

    if params[:category]
      @items = @items.where(:category_id => params[:category])
    end

    @items = @items.order("name ASC").page(params[:page]).per(10)
    @item = Item.new
    
  end

  def new
    @item = Item.new
  end
  
  def create
    @item = @user.items.build(params[:item])
    
    if @item.save
      redirect_to items_url, notice: "Item successfully created."
    else
      render :new, notice: "There was an error creating your item. Please try again."
    end
    
  end
  
  def show
    @item = @user.items.find(params[:id])
  end
  
  def edit
    @item = @user.items.find(params[:id])  
    
    respond_to do |format|
      format.js #:format => nil
      format.html
    end
          
  end
  
  def update
    puts @user.inspect
    @item = @user.items.find(params[:id])
    @item.update_attributes(params[:item])

    if @item.save
      redirect_to items_url, notice: "Item successfully updated."
      # respond_to do |format|
      #         format.js
      #       end
    else
      render :new, notice: "There was an error saving your item. Please try again."
    end    
  end
  
  def destroy
    @item = @user.items.find(params[:id])

    respond_to do |format|
      if @item.destroy
        format.html {redirect_to items_url, notice: "Item has been deleted."}
        format.js
      else
        format.html {render :index, notice: "Error deleting item."}
      end
    end
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:uid] = user.id
      redirect_to root_url, notice: "Welcome back, #{user.first_name}. Thank you for logging in."
    else
      redirect_to new_user_url, notice: "Login failed. Please try again or create an account."
    end
  end
  
  def destroy
    reset_session
    redirect_to root_url
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  # before_filter :current_user
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      session[:uid] = @user.id
      redirect_to items_url, notice: "Account successfully created! Get started by adding your items below."
    else
      render :new, notice: "There was an error creating your account. Please try again."
    end
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update_attributes(params[:user])
    redirect_to @user, notice: "Account updated."    
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to new_user_url, notice: "Your account has been deleted"
  end
  
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/items/_editform.html.haml
%div#edit_form
  %h3 Edit Item  

  %table
    =form_for(@item) do |form|
      %tr
        %td Name:
        %td=form.text_field :name
      %tr
        %td Acquired On:
        %td=form.date_select(:acquired_on, start_year:1992, end_year:2012, discard_day: true, order: [:month, :year])
      %tr
        %td Category:
        %td=form.collection_select :category_id, Category.all, :id, :title
      %tr
        %td Condition:
        %td=form.collection_select :condition_id, Condition.all, :id, :shape
      %tr
        %td= form.submit
  %span#cancel_button
    =link_to "Cancel", :action => "index"
  
  

app/views/items/_form.html.haml
%table
  =form_for(@item) do |form|
    %tr
      %td Name:
      %td=form.text_field :name
    %tr
      %td Acquired On:
      %td=form.date_select(:acquired_on, start_year:1992, end_year:2012, discard_day: true, order: [:month, :year])
    %tr
      %td Category:
      %td=form.collection_select :category_id, Category.all, :id, :title
    %tr
      %td Condition:
      %td=form.collection_select :condition_id, Condition.all, :id, :shape
    %tr
      %td= form.submit
%span#cancel_button
  = link_to "Cancel", items_url

app/views/items/_items.html.haml
%table.items
  %tr
    %th Item
    %th Acquired 
    %th Category
    %th Condition
    %th remove
    
  - @items.each do |item|
    %tr{:id => dom_id(item)}
      %td= link_to item.name, edit_item_url(item), class: 'item_link', :id => dom_id(item), :remote => true
      %td= item.acquired_on.strftime("%b %Y")
      %td= item.category.title
      %td= item.condition.shape
      %td= link_to "x", item, confirm: "Are you sure?", method: :delete, remote: true

app/views/items/edit.js.erb
$(".form_box").html("<%= j( render :partial=>'items/editform') %>");
// $("#<%= dom_id(@item)%>").effect("highlight", {}, 5000);

app/views/items/index.html.haml
%h2 Your Items
#search_form
  =form_tag items_url, :method => :get do
    /=text_field_tag :item,  (params[:item])
    = autocomplete_field :field, :item_name, autocomplete_item_name_path 
    =select_tag :category, options_from_collection_for_select(Category.all, :id, :title, params[:category]), prompt: 'Select a Category'
    =submit_tag 'Search' 
    %span.cancel_link=link_to "Reset", items_url

%div.clear

%div.new_link= link_to 'Add New Item', new_item_url

%div#new_form
  %h3 New Item
  = render 'form'

%span.form_box

= render 'items'

#pagination
  = paginate @items

app/views/items/new.html.haml
%h3 Add New Item

=render 'form'

app/views/items/show.html.haml
%h3= @item.name

%p 
  Acquired: 
  = @item.acquired_on.strftime('%b %d, %Y')
  
%p 
  Category: 
  = @item.category.title
  
%p
  Condition: 
  = @item.condition.shape
  
=link_to "Edit Item", edit_item_url(@item)

app/views/items/update.js.erb
$("#form_box").html("");

app/views/layouts/application.html.haml
!!! html
%html
  %head
    %titleHomestuffHAML
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Quattrocento+Sans'
    = stylesheet_link_tag 'http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/themes/redmond/jquery-ui.css'
    = csrf_meta_tags

  %body
    %header
      .menubar
        - if !logged_in?
          %ul
            = form_tag(sessions_create_url) do
              %li 
                Email: 
                =text_field_tag :email, nil, placeholder: "user@example.com" 
              %li 
                Password: 
                =password_field_tag :password, nil, placeholder: "password" 
                =submit_tag "Sign In"
        -else
          %ul
            %li Welcome, #{@user.first_name}
            %li= link_to "My Stuff", items_url
            %li= link_to "My Account", user_url(@user)
            %li= link_to "Logout", delete_session_url, method: "delete"
      
      %h1= link_to "HomeStuff", items_url
      %em The best place on the web to keep your stuff
    
    
    - if flash[:notice].present?
      #notice= notice
    
    = yield

app/views/users/_form.html.haml
%table
  =form_for(@user) do |form|
    %tr 
      %td First name: 
      %td=form.text_field :first_name, placeholder: "John"
    %tr 
      %td Last name: 
      %td=form.text_field :last_name, placeholder: "Doe"
    %tr 
      %td Email address 
      %td=form.text_field :email, placeholder: "John@example.com"
    %tr 
      %td Password: 
      %td=form.password_field :password, placeholder: "Password"
    %tr 
      %td Confirm Password: 
      %td=form.password_field :password_confirmation, placeholder: "Re-enter password"
    %tr
      %td=form.submit "Save"
  

app/views/users/edit.html.haml
%h2 Edit your account

=render 'form'

app/views/users/new.html.haml
#signup
  %h2 Sign Up!
  =render 'form'

app/views/users/show.html.haml
%h2 User Details

%p 
  %strong Name:
  = @user.first_name 
  = @user.last_name
  
%p 
  %strong Email:
  = @user.email
  
%p
  = link_to "Edit Account", edit_user_url(@user)

%p 
  = link_to "Delete account", user_url(@user), method: "delete", confirm: "Are you sure you want to delete your account?"